apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ${project.artifactId}
  namespace: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${project.artifactId}
      tier: backend
      version: ${project.version}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
        tier: backend
        version: ${project.version}
    spec:
      containers:
      - name: ${project.artifactId}
        image: ${docker.image.prefix}/${project.artifactId}:${docker.image.tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AUTH_SERVICE_BASEURL
          valueFrom:
            configMapKeyRef:
              name: auth-demo-config
              key: auth_service_baseUrl
        - name: SERVER_SERVLET_CONTEXT-PATH
          valueFrom:
            configMapKeyRef:
              name: auth-demo-config
              key: server_servlet_context-path
        #envFrom:
        #  - configMapRef:
        #    name: auth-demo-config
